### ISSUE TITLE
Accept an initial value

### ISSUE THREAD

**Issue by gabmontes** [sindresorhus/p-do-whilst#4]
Consider supporting the injection of an initial value into the loop. The code could be updated as follows:

```js
async function pDoWhilst(action, condition, initialValue) {
  const actionResult = await action(await initialValue);

  if (await condition(actionResult)) {
    return pDoWhilst(action, condition, actionResult);
  }

  return actionResult;
}
```

and that would allow managing the state internally,  instead of having to rely in an external variable:

```js
const finalCount = await pDoWhilst(
  (count) => count + 1,
  (count) => count < 5,
  0
);

console.log(finalCount);
//=> 5
```

Note that this change would be compatible and will not break the current API.

**Comment by gabmontes** [comment]
Waiting for comments from @sindresorhus and team before creating a PR out of https://github.com/gabmontes/p-do-whilst/tree/initial-value. It also depends on #5.

**Comment by sindresorhus** [comment]
👍
